# -*- coding: utf-8 -*-
from fastapi import APIRouter

from api.health import router as health_router
from api.nia import router as nia_router
from api.feedback import router as feedback_router
from api.product import router as product_router
from api.style import router as style_router
from api.makeup import router as makeup_router
from api.customization import router as customization_router

api_router = APIRouter()
api_router.include_router(health_router)          # /health, /ready, /version
api_router.include_router(nia_router)             # /nia/...
api_router.include_router(feedback_router)        # /feedback/...
api_router.include_router(product_router)         # /product/...
api_router.include_router(style_router)           # /style/...
api_router.include_router(makeup_router)          # /makeup/...
api_router.include_router(customization_router)   # /custom/...
